// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Email = "rahul@test.com",
                            IsActive = true,
                            Name = "Rahul Patil"
                        },
                        new
                        {
                            Id = 2,
                            Department = "HR",
                            Email = "sneha@test.com",
                            IsActive = true,
                            Name = "Sneha Sharma"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Finance",
                            Email = "amit@test.com",
                            IsActive = true,
                            Name = "Amit Kulkarni"
                        },
                        new
                        {
                            Id = 4,
                            Department = "IT",
                            Email = "priya@test.com",
                            IsActive = true,
                            Name = "Priya Deshmukh"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Sales",
                            Email = "rohit@test.com",
                            IsActive = true,
                            Name = "Rohit Singh"
                        },
                        new
                        {
                            Id = 6,
                            Department = "HR",
                            Email = "neha@test.com",
                            IsActive = true,
                            Name = "Neha Joshi"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Marketing",
                            Email = "karan@test.com",
                            IsActive = true,
                            Name = "Karan Mehta"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Support",
                            Email = "pooja@test.com",
                            IsActive = true,
                            Name = "Pooja Verma"
                        },
                        new
                        {
                            Id = 9,
                            Department = "IT",
                            Email = "aditya@test.com",
                            IsActive = true,
                            Name = "Aditya Patil"
                        },
                        new
                        {
                            Id = 10,
                            Department = "Finance",
                            Email = "simran@test.com",
                            IsActive = true,
                            Name = "Simran Kaur"
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Name = "Admin",
                            Password = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "employee@example.com",
                            Name = "Employee",
                            Password = "emp123",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            FromDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Personal Work",
                            Status = "Approved",
                            ToDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            FromDate = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Medical Leave",
                            Status = "Pending",
                            ToDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            FromDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Family Function",
                            Status = "Approved",
                            ToDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LeaveRequest", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
